import type {
  AggregationEntry,
  AggregationStore,
  Clock,
  ScheduledCheck,
  ScheduledStore,
} from '@air/engine';
import { createSystemClock } from '@air/engine';
import { Pool } from 'pg';
import type { PoolClient, PoolConfig, QueryResult, QueryResultRow } from 'pg';

import type { DemoNotification, DemoStore } from './rules.js';

type NotificationInput = Omit<DemoNotification, 'id' | 'createdAt'>;

export interface PostgresDemoStorageOptions {
  connectionString?: string;
  pool?: Pool;
  poolConfig?: PoolConfig;
  coreTeam?: Iterable<string>;
  clock?: Clock;
}

interface Queryable {
  query<T extends QueryResultRow = QueryResultRow>(text: string, values?: unknown[]): Promise<QueryResult<T>>;
}

interface NotificationRow extends QueryResultRow {
  id: number;
  delivery_id: string;
  event_name: string;
  rule_id: string;
  repository: string | null;
  message: string;
  url: string | null;
  aggregate_count: number | null;
  created_at: Date | string;
}

interface AggregationRow extends QueryResultRow {
  at_ms: string | number;
  delivery_id: string;
  payload: unknown;
}

interface CountRow extends QueryResultRow {
  count: number | string;
}

interface ScheduledRow extends QueryResultRow {
  rule_id: string;
  key_id: string;
  run_at_ms: string | number;
  scheduled_at_ms: string | number;
  deadline_ms: string | number | null;
  payload: unknown;
}

export class PostgresDemoStorage implements DemoStore {
  readonly coreTeam: Set<string>;
  readonly aggregationStore: AggregationStore;
  readonly scheduledStore: ScheduledStore;

  private readonly pool: Pool;
  private readonly ownsPool: boolean;

  constructor(opts: PostgresDemoStorageOptions = {}) {
    if (!opts.pool && !opts.connectionString && !opts.poolConfig?.connectionString) {
      throw new Error('PostgresDemoStorage requires a connectionString or pool');
    }

    this.pool = opts.pool ?? new Pool({
      ...opts.poolConfig,
      connectionString: opts.connectionString ?? opts.poolConfig?.connectionString,
    });
    this.ownsPool = !opts.pool;
    this.coreTeam = new Set(opts.coreTeam ?? ['alice', 'octocat']);

    const clock = opts.clock ?? createSystemClock();
    this.aggregationStore = new PostgresAggregationStore(this.pool, clock);
    this.scheduledStore = new PostgresScheduledStore(this.pool);
  }

  async init(): Promise<void> {
    await this.pool.query(`
      CREATE TABLE IF NOT EXISTS demo_notifications (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        delivery_id text NOT NULL,
        event_name text NOT NULL,
        rule_id text NOT NULL,
        repository text,
        message text NOT NULL,
        url text,
        aggregate_count integer,
        created_at timestamptz NOT NULL DEFAULT now()
      );

      CREATE TABLE IF NOT EXISTS demo_aggregation_entries (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        rule_id text NOT NULL,
        action_id text NOT NULL,
        key_id text NOT NULL,
        at_ms bigint NOT NULL,
        delivery_id text NOT NULL,
        payload jsonb NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now()
      );

      CREATE INDEX IF NOT EXISTS demo_aggregation_entries_bucket_idx
        ON demo_aggregation_entries (rule_id, action_id, key_id, at_ms, id);

      CREATE TABLE IF NOT EXISTS demo_scheduled_checks (
        rule_id text NOT NULL,
        key_id text NOT NULL,
        run_at_ms bigint NOT NULL,
        scheduled_at_ms bigint NOT NULL,
        deadline_ms bigint,
        payload jsonb NOT NULL,
        leased_until_ms bigint,
        PRIMARY KEY (rule_id, key_id)
      );

      CREATE INDEX IF NOT EXISTS demo_scheduled_checks_due_idx
        ON demo_scheduled_checks (run_at_ms, leased_until_ms);
    `);
  }

  async close(): Promise<void> {
    if (this.ownsPool) await this.pool.end();
  }

  async add(input: NotificationInput): Promise<DemoNotification> {
    const result = await this.pool.query<NotificationRow>(`
      INSERT INTO demo_notifications (
        delivery_id,
        event_name,
        rule_id,
        repository,
        message,
        url,
        aggregate_count
      ) VALUES ($1, $2, $3, $4, $5, $6, $7)
      RETURNING
        id,
        delivery_id,
        event_name,
        rule_id,
        repository,
        message,
        url,
        aggregate_count,
        created_at
    `, [
      input.deliveryId,
      input.eventName,
      input.ruleId,
      input.repository ?? null,
      input.message,
      input.url ?? null,
      input.aggregateCount ?? null,
    ]);

    return toNotification(result.rows[0]!);
  }

  async list(): Promise<DemoNotification[]> {
    const result = await this.pool.query<NotificationRow>(`
      SELECT
        id,
        delivery_id,
        event_name,
        rule_id,
        repository,
        message,
        url,
        aggregate_count,
        created_at
      FROM demo_notifications
      ORDER BY id ASC
    `);

    return result.rows.map(toNotification);
  }

  async clear(): Promise<void> {
    await this.pool.query('TRUNCATE demo_notifications RESTART IDENTITY');
  }
}

class PostgresAggregationStore implements AggregationStore {
  constructor(
    private readonly pool: Pool,
    private readonly clock: Clock,
  ) {}

  async append(
    ruleId: string,
    actionId: string,
    keyId: string,
    entry: AggregationEntry,
  ): Promise<void> {
    await this.pool.query(`
      INSERT INTO demo_aggregation_entries (
        rule_id,
        action_id,
        key_id,
        at_ms,
        delivery_id,
        payload
      ) VALUES ($1, $2, $3, $4, $5, $6::jsonb)
    `, [ruleId, actionId, keyId, entry.at, entry.deliveryId, toJson(entry.payload)]);
  }

  async list(ruleId: string, actionId: string, keyId: string, windowMs: number): Promise<AggregationEntry[]> {
    const now = this.clock.now();
    const result = await this.pool.query<AggregationRow>(`
      SELECT at_ms, delivery_id, payload
      FROM demo_aggregation_entries
      WHERE rule_id = $1
        AND action_id = $2
        AND key_id = $3
        AND at_ms >= $4
        AND at_ms <= $5
      ORDER BY at_ms ASC, id ASC
    `, [ruleId, actionId, keyId, now - windowMs, now]);

    return result.rows.map(toAggregationEntry);
  }

  async count(ruleId: string, actionId: string, keyId: string, windowMs: number): Promise<number> {
    return this.countWith(this.pool, ruleId, actionId, keyId, windowMs);
  }

  async appendAndCount(
    ruleId: string,
    actionId: string,
    keyId: string,
    entry: AggregationEntry,
    windowMs: number,
  ): Promise<number> {
    const client = await this.pool.connect();
    try {
      await client.query('BEGIN');
      await client.query(`
        INSERT INTO demo_aggregation_entries (
          rule_id,
          action_id,
          key_id,
          at_ms,
          delivery_id,
          payload
        ) VALUES ($1, $2, $3, $4, $5, $6::jsonb)
      `, [ruleId, actionId, keyId, entry.at, entry.deliveryId, toJson(entry.payload)]);
      const count = await this.countWith(client, ruleId, actionId, keyId, windowMs);
      await client.query('COMMIT');
      return count;
    } catch (err) {
      await rollback(client);
      throw err;
    } finally {
      client.release();
    }
  }

  async prune(olderThanMs: number): Promise<void> {
    await this.pool.query(
      'DELETE FROM demo_aggregation_entries WHERE at_ms < $1',
      [this.clock.now() - olderThanMs],
    );
  }

  private async countWith(
    queryable: Queryable,
    ruleId: string,
    actionId: string,
    keyId: string,
    windowMs: number,
  ): Promise<number> {
    const now = this.clock.now();
    const result = await queryable.query<CountRow>(`
      SELECT COUNT(*)::int AS count
      FROM demo_aggregation_entries
      WHERE rule_id = $1
        AND action_id = $2
        AND key_id = $3
        AND at_ms >= $4
        AND at_ms <= $5
    `, [ruleId, actionId, keyId, now - windowMs, now]);

    return Number(result.rows[0]?.count ?? 0);
  }
}

class PostgresScheduledStore implements ScheduledStore {
  constructor(private readonly pool: Pool) {}

  async enqueue(
    ruleId: string,
    keyId: string,
    runAt: number,
    payload: unknown,
    scheduledAt: number,
    deadline?: number,
  ): Promise<void> {
    await this.pool.query(`
      INSERT INTO demo_scheduled_checks (
        rule_id,
        key_id,
        run_at_ms,
        scheduled_at_ms,
        deadline_ms,
        payload,
        leased_until_ms
      ) VALUES ($1, $2, $3, $4, $5, $6::jsonb, NULL)
      ON CONFLICT (rule_id, key_id)
      DO UPDATE SET
        run_at_ms = EXCLUDED.run_at_ms,
        scheduled_at_ms = EXCLUDED.scheduled_at_ms,
        deadline_ms = EXCLUDED.deadline_ms,
        payload = EXCLUDED.payload,
        leased_until_ms = NULL
    `, [ruleId, keyId, runAt, scheduledAt, deadline ?? null, toJson(payload)]);
  }

  async claim(now: number, limit: number, leaseMs: number): Promise<ScheduledCheck[]> {
    if (limit <= 0) return [];

    const result = await this.pool.query<ScheduledRow>(`
      WITH due AS (
        SELECT rule_id, key_id
        FROM demo_scheduled_checks
        WHERE run_at_ms <= $1
          AND (leased_until_ms IS NULL OR leased_until_ms <= $1)
        ORDER BY run_at_ms ASC, rule_id ASC, key_id ASC
        LIMIT $2
        FOR UPDATE SKIP LOCKED
      )
      UPDATE demo_scheduled_checks AS scheduled
      SET leased_until_ms = $3
      FROM due
      WHERE scheduled.rule_id = due.rule_id
        AND scheduled.key_id = due.key_id
      RETURNING
        scheduled.rule_id,
        scheduled.key_id,
        scheduled.run_at_ms,
        scheduled.scheduled_at_ms,
        scheduled.deadline_ms,
        scheduled.payload
    `, [now, limit, now + Math.max(0, leaseMs)]);

    return result.rows
      .map(toScheduledCheck)
      .sort((a, b) => a.runAt - b.runAt);
  }

  async remove(ruleId: string, keyId: string): Promise<void> {
    await this.pool.query(
      'DELETE FROM demo_scheduled_checks WHERE rule_id = $1 AND key_id = $2',
      [ruleId, keyId],
    );
  }

  async reschedule(ruleId: string, keyId: string, newRunAt: number): Promise<void> {
    await this.pool.query(`
      UPDATE demo_scheduled_checks
      SET run_at_ms = $3,
          leased_until_ms = NULL
      WHERE rule_id = $1
        AND key_id = $2
    `, [ruleId, keyId, newRunAt]);
  }
}

export function createPostgresDemoStorage(opts: PostgresDemoStorageOptions): PostgresDemoStorage {
  return new PostgresDemoStorage(opts);
}

function toNotification(row: NotificationRow): DemoNotification {
  return {
    id: row.id,
    deliveryId: row.delivery_id,
    eventName: row.event_name,
    ruleId: row.rule_id,
    repository: row.repository ?? undefined,
    message: row.message,
    url: row.url ?? undefined,
    aggregateCount: row.aggregate_count ?? undefined,
    createdAt: new Date(row.created_at).toISOString(),
  };
}

function toAggregationEntry(row: AggregationRow): AggregationEntry {
  return {
    at: Number(row.at_ms),
    deliveryId: row.delivery_id,
    payload: row.payload,
  };
}

function toScheduledCheck(row: ScheduledRow): ScheduledCheck {
  return {
    ruleId: row.rule_id,
    keyId: row.key_id,
    runAt: Number(row.run_at_ms),
    scheduledAt: Number(row.scheduled_at_ms),
    deadline: row.deadline_ms === null ? undefined : Number(row.deadline_ms),
    payload: row.payload,
  };
}

function toJson(value: unknown): string {
  return JSON.stringify(value ?? null);
}

async function rollback(client: PoolClient): Promise<void> {
  try {
    await client.query('ROLLBACK');
  } catch {
    // Preserve the original transaction error.
  }
}
